vich_uploader:
    db_driver: orm

    mappings:
        evenements:
            uri_prefix: /images/evenements
            upload_destination: '%kernel.project_dir%/public/images/evenements'
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer

            inject_on_load: false
            delete_on_update: true
            delete_on_remove: true